direction: right
mpls: MPLS Enabled Core {
  p1 -- p2
  p1 -- p4
  p3 -- p2
  p3 -- p4
  p2 -- p4

  p1: P1 {
    shape: image
    icon: https://img.icons8.com/material/96/null/router.png
  }
  p2: P2 {
    shape: image
    icon: https://img.icons8.com/material/96/null/router.png
  }
  p3: P3 {
    shape: image
    icon: https://img.icons8.com/material/96/null/router.png
  }
  p4: P4 {
    shape: image
    icon: https://img.icons8.com/material/96/null/router.png
  }
}
pe1: PE1 {
  shape: image
  icon: https://img.icons8.com/material/96/null/router.png
}
pe2: PE2 {
  shape: image
  icon: https://img.icons8.com/material/96/null/router.png
}
pe3: PE3 {
  shape: image
  icon: https://img.icons8.com/material/96/null/router.png
}
ce1: CE1 {
  shape: image
  icon: https://img.icons8.com/material/96/null/router.png
}
ce2: CE2 {
  shape: image
  icon: https://img.icons8.com/material/96/null/router.png
}
ce3: CE3 {
  shape: image
  icon: https://img.icons8.com/material/96/null/router.png
}

pe1 -- mpls.p1
pe1 -- mpls.p3
mpls.p1 -- pe2
mpls.p2 -- pe2
mpls.p2 -- pe3
mpls.p4 -- pe3
ce1 -- pe1
ce2 -- pe2
ce3 -- pe3
