name: build with mike

on:
  release:
    types: [published, released]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      # - name: Fetch tags
      #   run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build And Deploy
        id: builddeploy
        run: |
          pip3 install -r requirements.txt
          ./tags.sh